// Mate in 1 — set C: generated in bulk, filtered by the engine, hand-curated
// for legible geometry (rook/bishop batteries, knight pairs, promotions,
// a discovered check) — no repeats of set A/B's named patterns.
'use strict';
var NG = typeof window !== 'undefined' ? (window.NG = window.NG || {}) : (globalThis.NG = globalThis.NG || {});
NG.PUZZLES = NG.PUZZLES || [];
NG.PUZZLES.push(
  { fen:'7k/4Q3/3K4/5R2/8/8/8/8 w - - 0 1', task:'White to move — mate in 1', solution:'1. Rf8#', note:'The queen alone owns the entire seventh rank, so the rook needs only the eighth: two officers, two ranks, and nothing left uncovered.' },
  { fen:'3B1K1k/8/6B1/8/8/8/8/8 w - - 0 1', task:'White to move — mate in 1', solution:'1. Bf6#', note:'One bishop crosses the board to arrive beside its twin and deliver the check itself. The twin never moves; the white king, standing close by, covers what remains.' },
  { fen:'8/4N3/6p1/8/5KBk/8/8/8 w - - 0 1', task:'White to move — mate in 1', solution:'1. Nxg6#', note:'The knight captures the last defending pawn and gives check in the same stroke; the white king, one square off, and a bishop beside it cover everything else.' },
  { fen:'8/8/8/8/2R5/2K5/2B5/k7 w - - 0 1', task:'White to move — mate in 1', solution:'1. Ra4#', note:'Rook, king, and bishop stand stacked one square apart on the same file, each already covering one escape square, before the rook slides sideways to strike from the file beside it.' },
  { fen:'8/8/8/8/6R1/6K1/4N3/7k w - - 0 1', task:'White to move — mate in 1', solution:'1. Rh4#', note:'The rook checks from three squares down the file it will finish on, not from beside the king. The white king covers what is close, and a distant knight guards the one square that matters.' },
  { fen:'8/8/8/8/1B2K3/8/2Q5/k7 w - - 0 1', task:'White to move — mate in 1', solution:'1. Bc3#', note:'The bishop’s own check reaches into the corner and its neighbouring square at the same time; the queen, posted well away, quietly owns the two squares the bishop cannot reach.' },
  { fen:'k7/8/8/8/1KQ5/4B3/8/8 w - - 0 1', task:'White to move — mate in 1', solution:'1. Qc8#', note:'The queen alone covers two of the three escape squares the instant she arrives beside the king; the third has belonged to a bishop on the far wing from the start.' },
  { fen:'1K1k4/8/5N2/N7/8/8/8/8 w - - 0 1', task:'White to move — mate in 1', solution:'1. Nc6#', note:'One knight has guarded two flight squares from a distance since long before this move; the white king covers two more just by standing close. The second knight only has to step forward to finish the job.' },
  { fen:'8/3N3k/5B2/7K/2B5/8/8/8 w - - 0 1', task:'White to move — mate in 1', solution:'1. Nf8#', note:'Two bishops on different diagonals cover four of the king’s five escape squares. The white king covers the last one just by standing close, and the knight lands on the only square left, checking as it goes.' },
  { fen:'3k4/1PR5/3p4/1K6/8/Q7/8/8 w - - 0 1', task:'White to move — mate in 1', solution:'1. b8=Q#', note:'A pawn is crowned on the very rank it needs to control, and the new queen commands that whole rank in both directions at once; a rook already stationed one rank back closes off everything behind her.' },
  { fen:'7k/5P2/8/8/5Q2/8/4K3/8 w - - 0 1', task:'White to move — mate in 1', solution:'1. Qh6#', note:'A pawn one square from crowning never has to move again. Merely standing on f7, it guards the one corner square the queen’s own check leaves open.' },
  { fen:'8/8/8/2R5/6K1/8/4R3/k7 w - - 0 1', task:'White to move — mate in 1', solution:'1. Rc1#', note:'One rook never moves at all, having already covered an entire rank; the other simply steps down its own file to strike.' },
  { fen:'8/8/8/8/3B2KQ/7p/8/7k w - - 0 1', task:'White to move — mate in 1', solution:'1. Qxh3#', note:'The queen captures the only pawn still guarding the king and checks with the same move; a bishop posted on an entirely different diagonal has already claimed the square she cannot reach.' },
  { fen:'8/8/8/4q3/8/4k3/5p2/7K b - - 0 1', task:'Black to move — mate in 1', solution:'1... f1=Q#', note:'One queen has watched the far corner from far away the whole game; her newly crowned replacement is born on the mating square itself and covers everything else alone.' },
  { fen:'8/8/8/8/6k1/4q3/4r3/7K b - - 0 1', task:'Black to move — mate in 1', solution:'1... Qc1#', note:'The rook never leaves the rank it already commands; the queen alone peels away to a completely different file to strike the final blow.' },
  { fen:'8/8/8/3r4/2b5/5k2/1P6/K7 b - - 0 1', task:'Black to move — mate in 1', solution:'1... Rd1#', note:'The defending king’s own pawn, still standing where the game began, blocks the one square that might have saved it, and a bishop across the board was already covering the other.' },
  { fen:'8/8/8/3k1n2/8/8/5q2/7K b - - 0 1', task:'Black to move — mate in 1', solution:'1... Ng3#', note:'The knight never covers a single flight square; its whole job is the check itself, since the queen alone already commands everywhere the king might run.' },
  { fen:'7K/6P1/8/6q1/6r1/8/8/1k6 b - - 0 1', task:'Black to move — mate in 1', solution:'1... Qxg7#', note:'Rook and queen have stood on the same file the entire time; the queen only has to clear away the one pawn blocking her view of the corner, and the rook behind her does the rest.' },
  { fen:'Knq5/8/8/8/6k1/8/8/8 b - - 0 1', task:'Black to move — mate in 1', solution:'1... Nc6#', note:'The knight steps aside, and it is the queen behind it, not the knight, that delivers the check; the knight’s own new square happens to seal both squares the queen cannot reach.' }
);
