// Mate in 3.
'use strict';
var NG = typeof window !== 'undefined' ? (window.NG = window.NG || {}) : (globalThis.NG = globalThis.NG || {});
NG.PUZZLES = NG.PUZZLES || [];
NG.PUZZLES.push(
  { fen:'6k1/5p1p/8/8/8/8/B7/K1B4R w - - 0 1', task:'White to move — mate in 3', solution:'1. Bh6 Kh8  2. Rg1 f6  3. Rg8#', note:'One bishop move seals both squares beside the king at once; the rook then simply walks up the file already made safe for it.' },
  { fen:'6k1/P6p/8/7B/8/8/8/4B1K1 w - - 0 1', task:'White to move — mate in 3', solution:'1. Bc3 h6  2. a8=Q+ Kh7  3. Qh8#', note:'The queen who delivers mate is born on the far side of the board, a pawn’s silent promotion timed to a bishop’s quiet opening move near the king.' },
  { fen:'k7/2p5/1B4Q1/8/5K2/8/8/8 w - - 0 1', task:'White to move — mate in 3', solution:'1. Qc6+ Kb8  2. Qxc7+ Ka8  3. Qa7#', note:'The bishop has guarded the queen’s mating square since the position began; the queen only has to arrive once the last pawn is gone.' },
  { fen:'k4K2/2p5/1p6/2Q1N3/8/8/8/8 w - - 0 1', task:'White to move — mate in 3', solution:'1. Qxc7 b5  2. Nc6 b4  3. Qb8#', note:'A single knight hop quietly seals the corner’s escape square for good, and the queen simply claims what is left.' },
  { fen:'k7/8/1p6/5Q2/1K6/8/8/4B3 w - - 0 1', task:'White to move — mate in 3', solution:'1. Qc8+ Ka7  2. Bg3 b5  3. Bf2#', note:'The finishing diagonal is not the one the bishop starts on; it takes a detour to find the line that actually reaches the king.' },
  { fen:'8/8/8/6N1/8/Q5pp/2K5/7k w - - 0 1', task:'White to move — mate in 3', solution:'1. Qxg3 h2  2. Qf3+ Kg1  3. Nh3#', note:'The queen spends two moves clearing the king’s cover; the knight, waiting on the flank, needs only one leap once the cover is gone.' },
  { fen:'5B2/7K/6Q1/8/8/8/7p/7k w - - 0 1', task:'White to move — mate in 3', solution:'1. Qc2 Kg1  2. Bc5+ Kh1  3. Qe4#', note:'The queen takes the long way around the board while a single bishop check does the actual herding.' },
  { fen:'3k3K/4b1P1/8/8/8/q7/8/8 b - - 0 1', task:'Black to move — mate in 3', solution:'1... Qh3+  2. Kg8 Kd7  3. Kf7 Qe6#', note:'White’s own pawn, one step from queening, never gets the chance. It spends the whole line blocking its own king’s escape instead.' },
  { fen:'8/5q2/8/7k/2b5/8/6P1/7K b - - 0 1', task:'Black to move — mate in 3', solution:'1... Qf2  2. Kh2 Bd5  3. Kh3 Qxg2#', note:'A single bishop move, played from well off to the side, quietly claims both the king’s last flight square and the square the queen is about to capture.' },
  { fen:'7K/5P2/1q4b1/8/8/8/5k2/8 b - - 0 1', task:'Black to move — mate in 3', solution:'1... Qf6+  2. Kg8 Qxf7+  3. Kh8 Qh7#', note:'One bishop, posted along the long diagonal, blankets three of the king’s escape squares at once; the queen’s whole task is removing the one pawn still in the way.' },
  { fen:'8/8/1K6/8/R7/5Np1/8/7k w - - 0 1', task:'White to move — mate in 3', solution:'1. Ra2 g2  2. Ra1+ g1=Q+  3. Rxg1#', note:'A pawn reaches the far rank and becomes a queen for exactly one move, captured the instant it is born, completing the mating net instead of breaking it.' },
  { fen:'8/8/2b5/8/4r3/8/1P6/K3k3 b - - 0 1', task:'Black to move — mate in 3', solution:'1... Ra4+  2. Kb1 Be4+  3. Kc1 Rc4#', note:'Rook and bishop check in turn, each pushing the king one square closer to the corner it can never leave.' },
  { fen:'6rk/8/8/8/8/7P/8/1n5K b - - 0 1', task:'Black to move — mate in 3', solution:'1... Nd2  2. Kh2 Nf3+  3. Kh1 Rg1#', note:'The knight crosses the board in two hops to land the check that pushes the king back into its own corner, where the rook is already waiting.' },
  { fen:'7k/7p/1B5K/8/6B1/8/8/8 w - - 0 1', task:'White to move — mate in 3', solution:'1. Bc5 Kg8  2. Be6+ Kh8  3. Bd4#', note:'Two bishops alone corner the king, one holding a diagonal while the other closes in for the final check, with no other piece needed at all.' },
  { fen:'8/8/8/8/4b3/bPk5/1P6/K7 b - - 0 1', task:'Black to move — mate in 3', solution:'1... Bxb2+  2. Ka2 Kc2  3. b4 Bd5#', note:'Black’s own bishop captures White’s last shelter with check, then a quiet king step and a second bishop’s move do the rest.' },
  { fen:'3R4/8/8/8/6B1/4K1p1/8/7k w - - 0 1', task:'White to move — mate in 3', solution:'1. Bf3+ Kh2  2. Rh8+ Kg1  3. Rh1#', note:'The bishop’s check herds the king from a distance; the rook, already on the back rank, only has to slide into the file left open.' },
  { fen:'7k/6pN/6p1/8/2K5/8/2R5/8 w - - 0 1', task:'White to move — mate in 3', solution:'1. Ng5 Kg8  2. Rf2 Kh8  3. Rf8#', note:'The knight abandons its post beside the king entirely: its real job was clearing a path for the rook, which mates from a file the knight never touched.' },
  { fen:'k7/4K3/p7/8/3N4/4R3/8/8 w - - 0 1', task:'White to move — mate in 3', solution:'1. Rb3 a5  2. Nc6 a4  3. Rb8#', note:'A single knight hop seals the last square that could have saved the king from the rook’s open file.' },
  { fen:'3N3k/5p2/6p1/8/2Q5/8/8/1K6 w - - 0 1', task:'White to move — mate in 3', solution:'1. Qxf7 g5  2. Qg6 g4  3. Nf7#', note:'The knight has crouched beside the king since the very first move; the queen’s task is simply to clear both pawns so it can strike.' },
  { fen:'7k/5p2/6p1/8/7B/8/4K3/R7 w - - 0 1', task:'White to move — mate in 3', solution:'1. Bf6+ Kg8  2. Ra8+ Kh7  3. Rh8#', note:'The bishop’s check clears the diagonal in passing; the same rook then needs only the rank, then the file, to finish what the check began.' },
  { fen:'1k6/8/8/8/3n1q2/1P6/2P5/K7 b - - 0 1', task:'Black to move — mate in 3', solution:'1... Qc1+  2. Ka2 Qxc2+  3. Ka3 Qxb3#', note:'One knight, planted in the centre from the very first move, is all the protection the queen needs to eat both pawns on the way to mate.' },
  { fen:'K7/1P6/1P6/5b2/3q4/8/8/7k b - - 0 1', task:'Black to move — mate in 3', solution:'1... Be4  2. Kb8 Qd7  3. Ka8 Qxb7#', note:'The bishop slides onto the long diagonal aimed at the corner first; only once it is watching does the queen move in to take the defending pawn.' },
  { fen:'k2B4/1p3K2/8/1R6/8/8/8/8 w - - 0 1', task:'White to move — mate in 3', solution:'1. Bb6 Kb8  2. Rc5 Ka8  3. Rc8#', note:'The bishop steps once and never moves again, sealing the only square the king briefly had while the rook manoeuvres into place for the rank.' }
);
