'use strict';
var NG = typeof window !== 'undefined' ? (window.NG = window.NG || {}) : (globalThis.NG = globalThis.NG || {});
NG.CONCEPTS = NG.CONCEPTS || [];
NG.CONCEPTS.push(
  { tag:'Dansk', title:'Overskud', body:'Literally “surplus”: the spare mental energy to be patient, generous, or playful. You don’t <em>find</em> time for people; you need overskud for them.' },
  { tag:'Dansk', title:'Arbejdsglæde', body:'“Work-joy”: a single Danish word for finding genuine happiness in one’s work. Scandinavian languages have it; most others need a sentence.' },
  { tag:'Dansk', title:'Fingerspidsfornemmelse', body:'“Fingertip-feeling.” The intuitive touch for a delicate situation that no rulebook can teach. Knowing exactly how far to go, and no further.' },
  { tag:'Dansk', title:'Pyt', body:'A tiny word for letting small annoyances go. Danish schools even keep a physical <em>pyt-knap</em> to press. Not resignation; a decision that this one is not worth your overskud.' },
  { tag:'Dansk', title:'Ildsjæl', body:'“Fire-soul”: the volunteer who keeps the club, the festival or the association running on sheer inner flame. Danish civil society is built from ildsjæle.' },
  { tag:'Dansk', title:'Vemod', body:'A soft, quiet melancholy. Sadness without an object, closer to longing than to grief. The Danish autumn, distilled into two syllables.' },
  { tag:'Dansk', title:'Tidsoptimist', body:'“Time-optimist”: the person who sincerely believes the drive takes ten minutes, every single time it has taken twenty. A diagnosis, delivered affectionately.' },
  { tag:'Dansk', title:'Træls', body:'Jutland’s all-purpose word for tiresome. The delayed train, the flat tyre, the form that must be printed to be signed. Mild enough to say to anyone, precise enough to need no more.' },
  { tag:'Dansk', title:'Janteloven', body:'The Law of Jante, from Sandemose’s 1933 novel: <em>don’t think you are anything special</em>. Denmark’s unwritten levelling code. Resented, defended, and obeyed in equal measure.' },
  { tag:'Dansk', title:'Nærvær', body:'Literally “near-being”: full presence in the room you are actually in. The opposite of a glance at the phone; the quality hygge quietly depends on.' },
  { tag:'Dansk', title:'Fjumreår', body:'“Fumble-year.” The gap year between school and study, officially frowned upon and privately treasured. A word that admits wandering has value.' },
  { tag:'Dansk', title:'Hygge', body:'The postcard version is candles and blankets. The lived version is a mild social contract: raising conflict, complaint or bad news mid-hygge is a small transgression of its own.' },
  { tag:'Dansk', title:'Frisind', body:'Literally “free-mind”: a specifically Danish tolerance for how others choose to live. It is the word behind Denmark becoming, in 1989, the first country to legally recognise same-sex partnerships.' },
  { tag:'Dansk', title:'Dannelse', body:'Roughly “Bildung.” The cultivation of character and judgement that schooling is supposed to produce alongside the diploma. A Dane can hold a degree and still be told they lack <em>dannelse</em>.' },
  { tag:'Dansk', title:'Tillid', body:'Trust, treated as public infrastructure rather than private virtue. It is why strollers nap outside cafés unattended, and why self-service honesty boxes survive at all.' },
  { tag:'Dansk', title:'Skæg', body:'The same word means “beard” and “funny”: a coincidence Danes stopped noticing generations ago, and foreigners never quite do.' },
  { tag:'Dansk', title:'Gift', body:'One word for “married” and “poison”: the joke writes itself, and every Dane has made it about their own wedding at least once.' },
  { tag:'Dansk', title:'Kæreste', body:'Literally “dearest,” the superlative of <em>kær</em>, and the everyday word for boyfriend or girlfriend, used by teenagers and pensioners without distinction.' },
  { tag:'Dansk', title:'Jo', body:'A small word with no English equivalent: it answers a negative statement with “yes, in fact,” where a plain yes would only confirm the negative.' },
  { tag:'Dansk', title:'Nå', body:'One syllable that means “oh,” “I see,” “well then” or “here we go,” depending entirely on tone. The word supplies almost none of its own meaning.' },
  { tag:'Dansk', title:'Værsgo', body:'Contracted from <em>vær så god</em>, “be so good”: said while handing over a plate, a seat, or the floor in conversation. Function over ceremony.' },
  { tag:'Dansk', title:'Rar', body:'A false friend: rar means kind or pleasant, not scarce. <em>En rar mand</em> is simply a nice man, no rarity implied.' },
  { tag:'Dansk', title:'Eventuelt', body:'A false friend: eventuelt means “possibly” or “if applicable,” not “in the end.” Danish meeting agendas often close with it, a catch-all slot for whatever comes up.' },
  { tag:'Dansk', title:'Aktuelt', body:'A false friend. Aktuelt means “currently relevant,” not “actually.” Reach for faktisk when you mean the English sense; aktuelt describes what is in the news right now.' },
  { tag:'Dansk', title:'Blanket', body:'A false friend: a blanket in Danish is a form to fill out, not something to sleep under. Danish bureaucracy runs on them.' },
  { tag:'Dansk', title:'Novelle', body:'A false friend: a novelle is a short story; a novel is a roman. Danish keeps the two apart more strictly than English does.' },
  { tag:'Dansk', title:'Gymnasium', body:'A false friend. A gymnasium in Denmark is the three-year school before university, not a place to lift weights. No dumbbells involved.' },
  { tag:'Dansk', title:'Advokat', body:'A false friend: advokat means lawyer, never the fruit, which keeps its own name, avocado, unchanged. The two words share nothing but a coincidence of sound.' },
  { tag:'Dansk', title:'Time', body:'A false friend: a time is an hour, or a school lesson. The abstract concept English calls “time” is a separate word entirely, <em>tid</em>.' },
  { tag:'Dansk', title:'Fart', body:'A false friend that delights every English-speaking beginner. <em>Fart</em> simply means speed. Road signs reading fartgrænse are only announcing the speed limit.' },
  { tag:'Dansk', title:'Det bløde d', body:'The blødt d is a consonant most foreign tongues have never attempted: a d where the tongue approaches but never quite touches, more air than sound. Danish children take years to master it too.' },
  { tag:'Dansk', title:'En eller et', body:'Every noun is quietly en or et, and no rule reliably predicts which: just en bil, et hus, learned one word at a time, for life.' },
  { tag:'Dansk', title:'Sammensætning', body:'Danish builds words by simple concatenation. <em>Arbejdsløshedsunderstøttelse</em> is just arbejdsløshed, unemployment, plus understøttelse, support. No hyphen, no space, no apology.' },
  { tag:'Dansk', title:'Stød', body:'A tiny catch in the voice: a glottal creak that can be the only difference between two otherwise identical words. Neither Swedish nor Norwegian has it.' },
  { tag:'Dansk', title:'Halvtreds', body:'Halvtreds, fifty, is short for halvtredsindstyve, literally <em>half-third times twenty</em>. Tres, halvfjerds, firs and halvfems hide the same vigesimal arithmetic, just better disguised.' },
  { tag:'Dansk', title:'Andelsbolig', body:'A flat you never quite own outright. You buy a share in the association that owns the building, at a price its own members help set.' },
  { tag:'Dansk', title:'Kolonihave', body:'A garden colony on rented public land, complete with a tiny house too small to legally live in year-round, and waiting lists in Copenhagen that stretch for years.' },
  { tag:'Dansk', title:'Folkehøjskole', body:'A residential school for adults with no exams, no grades and no qualification at the end: just weeks or months spent living, discussing and singing together.' },
  { tag:'Dansk', title:'Foreningsliv', body:'Denmark runs partly on volunteer-led clubs, each self-governed through an annual generalforsamling: sports, choirs, rescue squads, garden committees. Joining one is closer to <em>civic duty</em> than hobby.' },
  { tag:'Dansk', title:'Bofællesskab', body:'The word English translates as “cohousing” is <em>bofællesskab</em>: private homes clustered around shared kitchens, gardens and tools. The modern version of the idea began here, in the 1970s.' },
  { tag:'Dansk', title:'Efterskole', body:'A boarding-school year, usually between primary school and gymnasium, chosen by a large share of Danish teenagers each year. A deliberate pause to grow up somewhere that is not home.' },
  { tag:'Dansk', title:'Konfirmation', body:'A Lutheran coming-of-age ritual many Danish fourteen-year-olds still go through, church attendance or not: the theology has faded; the party, the gifts and the new suit have not.' },
  { tag:'Dansk', title:'Studenterhue', body:'The white sailor-style cap earned by finishing gymnasium, then worn for a truck tour of town, visiting each graduate’s home in turn, singing the whole way.' },
  { tag:'Dansk', title:'Fastelavn', body:'A pre-Lenten carnival where children in costume beat a barrel painted with a cat until it splits open and candy spills out. Nobody quite remembers why it was ever a cat.' },
  { tag:'Dansk', title:'Sankt Hans', body:'Midsummer bonfires on the beach, each topped with a straw witch sent up in flames toward Bloksbjerg, where folklore says Danish witches once flew to meet the devil.' },
  { tag:'Dansk', title:'Store Bededag', body:'A public holiday since 1686, quietly abolished in 2023 to help fund defence spending: one of the few times in Danish history a day off has been legislated away.' },
  { tag:'Dansk', title:'Ugler i mosen', body:'Literally “there are owls in the bog”: the standard warning that something here does not add up, some hidden catch still waiting to be found.' },
  { tag:'Dansk', title:'Halv pelikan', body:'Literally “it is blowing half a pelican.” A perfectly serious way to say it is extremely windy outside. Danish weather idioms rarely bother with restraint.' },
  { tag:'Dansk', title:'Gå agurk', body:'Literally “to go cucumber,” youth slang for losing your composure entirely, recent enough to still sound like slang to anyone over forty.' },
  { tag:'Dansk', title:'Høne at plukke', body:'Literally “to have a hen to pluck with someone”: the Danish version of having a bone to pick. Same grievance, an entirely different farmyard.' },
  { tag:'Dansk', title:'Ko på isen', body:'Literally “there is no cow on the ice.” The Danish way of saying relax, nothing is actually at risk. A stranded cow on a frozen lake used to be a real emergency.' },
  { tag:'Dansk', title:'Fanden på væggen', body:'Literally “to paint the devil on the wall,” said to anyone predicting disaster so vividly they seem to be inviting it. Superstition, dressed as a figure of speech.' },
  { tag:'Dansk', title:'Tungen lige i munden', body:'Literally “to hold your tongue straight in your mouth”: the image for total concentration on a fiddly task. Anyone threading a needle already knows the feeling.' },
  { tag:'Dansk', title:'Næse og mund', body:'Literally “to lose your nose and mouth.” Utter astonishment, the kind that seems to rearrange the whole face. English settles for “dumbfounded”; Danish shows the damage.' },
  { tag:'Dansk', title:'Hår i postkassen', body:'Literally “to stand with your hair caught in the mailbox,” trapped in an awkward position of your own making, with no graceful way to step back.' },
  { tag:'Dansk', title:'Ude i skoven', body:'Literally “to be totally out in the forest”: hopelessly wrong, lost in an argument that <em>wandered off the path</em> a while ago.' },
  { tag:'Dansk', title:'Rotter på loftet', body:'Literally “to have rats in the attic.” A polite way of suggesting someone is not thinking quite straight. The Danish attic, like the English belfry, is never structural.' },
  { tag:'Dansk', title:'Benene på nakken', body:'Literally “to put your legs on your neck”: to flee at full speed. An anatomically impossible image for a very ordinary feeling.' },
  { tag:'Dansk', title:'Koste kassen', body:'Literally “to cost the cash box.” Danish for eye-wateringly expensive. Whatever it is, the till is not going to recover.' },
  { tag:'Dansk', title:'Hunden på hårene', body:'Literally “don’t judge the dog by its coat”: the Danish equivalent of “don’t judge a book by its cover,” with fur standing in for a paperback jacket.' }
);
