'use strict';
var NG = typeof window !== 'undefined' ? (window.NG = window.NG || {}) : (globalThis.NG = globalThis.NG || {});
NG.CONCEPTS = NG.CONCEPTS || [];
NG.CONCEPTS.push(
  { tag:'History', title:'The year without a summer', body:'Mount Tambora’s 1815 eruption cooled the planet enough that 1816 brought snow in June to New England. Trapped indoors by that ruined summer at Lake Geneva, Mary Shelley began writing <em>Frankenstein</em>.' },
  { tag:'History', title:'The Antikythera mechanism', body:'Pulled from a shipwreck in 1901, this ancient bronze device of interlocking gears once predicted eclipses and tracked the calendar. Nothing built with comparable complexity appeared again in Europe for well over a thousand years.' },
  { tag:'History', title:'The Library of Alexandria', body:'No single fire ended it, whatever the legend says. Its decline was slow: funding cuts, wars, and centuries of neglect thinning the collection long before the last scholars ever drifted away.' },
  { tag:'History', title:'Ada Lovelace’s notes', body:'In 1843, Ada Lovelace annotated a paper on Babbage’s unbuilt Analytical Engine with notes far longer than the original, including what many now call the first published algorithm written for a machine.' },
  { tag:'History', title:'The Carrington Event', body:'In September 1859, the largest solar storm on record lit the night sky as far south as the Caribbean and sent telegraph lines sparking on their own. A storm of that size today would find a much more wired world waiting.' },
  { tag:'History', title:'The longbow at Agincourt', body:'In 1415, English archers with six-foot yew longbows broke a much larger French force in the mud near Agincourt. A trained longbowman could loose several arrows a minute, drawing a bow that could take a <em>lifetime</em> of practise to master.' },
  { tag:'History', title:'The Danelaw', body:'After years of Viking invasion, Alfred the Great beat the Danish leader Guthrum at Edington in 878; a later treaty between them drew a border along the Thames, the Lea and Watling Street. English law to the west, Danish law and custom to the east. The line still shows up in English place names today.' },
  { tag:'History', title:'The Hanseatic League', body:'A confederation of merchant guilds and towns, not a state, quietly controlled trade across the Baltic and North Sea for some four centuries. Lübeck was its unofficial capital; no single ruler was ever in charge.' },
  { tag:'History', title:'The Øresund toll', body:'From 1429 to 1857, every merchant ship passing between Denmark and Sweden paid a toll to the Danish crown, for centuries one of the country’s largest sources of income. It took an international treaty to finally end it.' },
  { tag:'History', title:'The first transatlantic cable', body:'In August 1858, a cable laid across the ocean floor let Queen Victoria and President Buchanan exchange telegrams in hours instead of weeks. It worked for barely a month before failing; a durable connection took until 1866.' },
  { tag:'History', title:'Semmelweis and the sceptical doctors', body:'In 1847, Ignaz Semmelweis found that doctors who washed their hands with chlorinated lime between the morgue and the maternity ward cut childbed-fever deaths dramatically. His colleagues were offended by the implication and largely ignored him.' },
  { tag:'History', title:'The Bronze Age collapse', body:'Within a few decades around 1200 BCE, the palace civilisations of the Eastern Mediterranean, such as Mycenaean Greece, the Hittites, and several Levantine cities, broke down almost together. Historians still debate how much was invasion, drought, or a trade network too interconnected to survive the shock.' },
  { tag:'History', title:'Göbekli Tepe', body:'Carved stone pillars in southeastern Turkey, raised around 9600 BCE by people with no farming and no pottery, predate Stonehenge by more than six thousand years. It rewrote assumptions about which came first, monuments or agriculture.' },
  { tag:'History', title:'The Rosetta Stone', body:'French soldiers found it near Rosetta, Egypt, in 1799: a single decree carved in three scripts, one of them Greek. That overlap let Jean-François Champollion crack Egyptian hieroglyphs in 1822, after centuries of failed attempts.' },
  { tag:'History', title:'Gutenberg’s press', body:'Around 1450 in Mainz, Johannes Gutenberg combined movable metal type with a screw press adapted from winemaking. A scribe once needed months to copy a single Bible; his workshop could turn out hundreds.' },
  { tag:'History', title:'The Great Fire of London', body:'A bakery fire on Pudding Lane in September 1666 burned for four days and destroyed most of the medieval City of London. Official records counted only a handful of deaths: historians suspect the true toll among the poor went unrecorded.' },
  { tag:'History', title:'The Plague of Justinian', body:'Starting in 541 CE, a pandemic swept the Byzantine Empire so severe that contemporaries described Constantinople running out of room to bury its dead. Genetic analysis of skeletons has since confirmed the same plague bacterium behind the later <em>Black Death</em>.' },
  { tag:'History', title:'Pompeii', body:'The eruption of Vesuvius in 79 CE buried Pompeii under ash so completely that the city was rediscovered largely intact some sixteen centuries later. The ash preserved not just buildings but the exact shapes of the people caught inside it.' },
  { tag:'History', title:'The Dead Sea Scrolls', body:'A shepherd searching for a lost goat found the first jar of manuscripts in a cave near Qumran in 1947. Among them were copies of the Hebrew Bible a thousand years older than any previously known.' },
  { tag:'History', title:'Suez, 1956', body:'Nasser nationalised the canal; Britain, France and Israel invaded to take it back, and withdrew when Washington declined to support them and sterling buckled. The week the old empires learned who now set the rules.' },
  { tag:'History', title:'The longitude problem', body:'For centuries, sailors could measure latitude easily but not longitude, and ships ran aground for want of it. A Yorkshire carpenter named John Harrison solved it not with astronomy but with a clock accurate enough to survive a rolling ship.' },
  { tag:'History', title:'The Voyager Golden Record', body:'Launched in 1977, each Voyager probe carries a gold-plated record of Earth’s sounds, music and images, curated by a committee led by Carl Sagan. It was built for an audience that may never listen, or may not <em>exist</em> yet.' },
  { tag:'History', title:'Penicillin', body:'In 1928, Alexander Fleming noticed that mould had killed the bacteria in a petri dish he had forgotten to clean. He nearly discarded it: the accident that followed became the first antibiotic.' },
  { tag:'History', title:'Eratosthenes measures the Earth', body:'Around 240 BCE, the Alexandrian librarian Eratosthenes compared the length of shadows at noon in two Egyptian cities to calculate the Earth’s circumference. Using nothing but geometry and a well, he landed strikingly close to the true figure.' },
  { tag:'History', title:'Vikings in North America', body:'Norse settlers built a small camp at L’Anse aux Meadows in Newfoundland around 1021 CE, dated by a solar storm’s signature preserved in the wood’s tree rings, nearly five centuries before Columbus ever sailed.' }
);
