'use strict';
var NG = typeof window !== 'undefined' ? (window.NG = window.NG || {}) : (globalThis.NG = globalThis.NG || {});
NG.CONCEPTS = NG.CONCEPTS || [];
NG.CONCEPTS.push(
  { tag:'Sun Tzu', title:'The acme of skill', body:'To fight and win every battle is not the height of skill — Sun Tzu ranked that below breaking the enemy’s resistance <em>without</em> a fight. The cheapest victory is the best one.' },
  { tag:'Sun Tzu', title:'Know the enemy, know yourself', body:'Know both, and a hundred battles hold no danger. Know only yourself, and you win half the time. Know neither, and you lose every one.' },
  { tag:'Sun Tzu', title:'All warfare is deception', body:'Appear weak when you are strong, and strong when you are weak; seem near when far, and far when near. Sun Tzu opened his treatise by declaring that war begins in the mind, not on the field.' },
  { tag:'Sun Tzu', title:'Speed is the essence of war', body:'Strike before the enemy is ready, by routes he never expected. Sun Tzu treated hesitation itself as a casualty — the fastest general spends the <em>least</em> blood.' },
  { tag:'Sun Tzu', title:'Attack the plan, not the city', body:'Best is to foil the enemy’s strategy; next, to break his alliances; next, to meet his army in open field. Besieging a walled city came last of all — the slowest, costliest way to win.' },
  { tag:'Sun Tzu', title:'The sheathed sword', body:'The general praised for a brilliant victory has usually already failed once. Sun Tzu rated higher the fighter who wins so cleanly that no battle is ever seen, and no one thinks to applaud.' },
  { tag:'Sun Tzu', title:'Choose the ground first', body:'The army that reaches the field first waits there rested; the army that hurries in second arrives exhausted before the first blow lands. Sun Tzu treated the choice of terrain as <em>half the battle</em>, settled before any sword was drawn.' },
  { tag:'Sun Tzu', title:'Calculations in the temple', body:'Before a soldier marched, Sun Tzu had the general reckon it all in the ancestral temple — the ruler’s support, the weather, the ground, the commander’s character, the discipline of the ranks. Whoever calculates more, generally wins more.' },
  { tag:'Sun Tzu', title:'The bent crossbow', body:'Energy is potential stored, not motion spent — a crossbow drawn fully back, waiting. Decision is only the trigger. Sun Tzu’s point was timing: the force was there all along; judgment decided the <em>release</em>.' },
  { tag:'Sun Tzu', title:'Without form', body:'The deepest disposition of troops leaves no shape for the enemy to read — not even his sharpest spies can map it, not even his wisest strategist can plan against it. Water has no constant shape either, which is why it always finds the <em>gap</em>.' },
  { tag:'Sun Tzu', title:'The stone rolling downhill', body:'A round stone sits still on flat ground; on a steep slope, it moves itself. Sun Tzu wanted commanders to build that slope — an arrangement of forces so favorable that momentum does the fighting instead of the men.' },
  { tag:'Sun Tzu', title:'Cheaper than an army', body:'A campaign could burn a thousand ounces of silver a day, yet Sun Tzu called it inhumane to withhold a fraction of that from spies merely to save money. Foreknowledge was the <em>cheapest</em> weapon in the whole arsenal.' },
  { tag:'Sun Tzu', title:'Knowing when not to fight', body:'Among the five things Sun Tzu named as deciding victory, the first was not strength or numbers — it was a general who could tell a fight worth having from one worth <em>avoiding</em>.' },
  { tag:'Sun Tzu', title:'No country benefits from a long war', body:'Sun Tzu opened his second chapter with arithmetic, not glory: an army of a hundred thousand burns a fortune every single day it stays in the field. Winning fast was not a preference — it was the whole economics of the thing.' },
  { tag:'Sun Tzu', title:'The golden bridge', body:'Sun Tzu did tell generals to leave a surrounded enemy a way out — a cornered force fights harder than a free one. The vivid phrase “golden bridge” came later, from European military writers, and simply <em>stuck</em> to him.' },
  { tag:'Sun Tzu', title:'Anger is not a strategy', body:'A ruler should never send an army to war merely to vent his temper, nor a general fight merely out of pique. Anger passes, Sun Tzu warned — but a ruined kingdom does not come back, and the dead stay dead.' },
  { tag:'Sun Tzu', title:'Five faults of a general', body:'Recklessness gets him killed; cowardice gets him captured; a hasty temper can be goaded into a trap; too much pride can be shamed into one; too much concern for his men can be exploited through them.' },
  { tag:'Sun Tzu', title:'The quotes he never wrote', body:'“Keep your friends close, your enemies closer” appears nowhere in the Art of War — that line is Hollywood. “Appear weak when you are strong” is genuine. Twenty-five centuries of fame made him a magnet for <em>everyone else’s</em> wisdom too.' },
  { tag:'Sun Tzu', title:'Invincibility is in your own hands', body:'A general can guarantee he will <em>not</em> be beaten — discipline, position, preparation are entirely his to control. Whether he gets to beat the enemy depends on the enemy’s own mistakes, which belong to no one but him.' },
  { tag:'Sun Tzu', title:'The direct and the indirect', body:'Five notes make every melody ever written; five colors make every shade ever seen. Sun Tzu used the arithmetic to make a point about war — combine the direct attack with the indirect maneuver, and the tactics become just as inexhaustible.' },
  { tag:'Sun Tzu', title:'Desperate ground', body:'Soldiers with an open retreat will take it; soldiers with none will fight like cornered animals instead. Of the nine kinds of terrain Sun Tzu catalogued, desperate ground produced — perversely — the <em>most determined</em> army of all.' },
  { tag:'Sun Tzu', title:'The snake of the Ch’ang mountains', body:'Strike its head, and the tail attacks; strike its tail, and the head attacks; strike its middle, and both ends attack at once. Sun Tzu wanted an army that moved like that single mythical serpent — every part defending every other.' },
  { tag:'Sun Tzu', title:'Wind, forest, fire, mountain', body:'Swift as wind, silent as forest, ravaging as fire, immovable as mountain — Sun Tzu’s four qualities of a moving army. More than two thousand years later, the Japanese warlord Takeda Shingen painted the same four words on his battle banners.' },
  { tag:'Sun Tzu', title:'The general’s drill', body:'Asked to prove himself, Sun Tzu drilled the king’s own concubines as soldiers. When the ranks dissolved into laughter, he executed the two he had named captains, over the king’s objections — and the next order was carried out in <em>total</em> silence.' },
  { tag:'Sun Tzu', title:'A 1772 arrival', body:'Europe met the Art of War through a French Jesuit missionary in Beijing, Father Amiot, whose 1772 translation reached Paris only two decades before Napoleon’s wars began. Two thousand years old, and still freshly arriving.' }
);
