#!/usr/bin/env node
'use strict';
// Generates docs/CONTENT-INDEX.md from the actual card data — never edit the
// index by hand. `--check` exits 1 if the committed index is stale (used by
// the pre-commit hook).
const fs = require('fs');
const path = require('path');

const root = path.join(__dirname, '..');

// content.js defines NG plus the base arrays; the per-tag files under
// tizen/js/content/ push into NG.CONCEPTS, and the per-set files under
// tizen/js/chess/ push into NG.PUZZLES / NG.POSITIONS. Flat content-*.js
// files are the transitional pre-assembly layout — load those too if present.
require(path.join(root, 'tizen', 'js', 'content.js'));
const contentDir = path.join(root, 'tizen', 'js', 'content');
if (fs.existsSync(contentDir)) {
  for (const f of fs.readdirSync(contentDir).sort()) {
    if (f.endsWith('.js')) { require(path.join(contentDir, f)); }
  }
}
const chessDir = path.join(root, 'tizen', 'js', 'chess');
if (fs.existsSync(chessDir)) {
  for (const f of fs.readdirSync(chessDir).sort()) {
    if (f.endsWith('.js')) { require(path.join(chessDir, f)); }
  }
}
for (const f of fs.readdirSync(path.join(root, 'tizen', 'js')).sort()) {
  if (/^content-.+\.js$/.test(f)) { require(path.join(root, 'tizen', 'js', f)); }
}

const NG = globalThis.NG;
const byTag = new Map();
for (const c of NG.CONCEPTS) {
  if (!byTag.has(c.tag)) { byTag.set(c.tag, []); }
  byTag.get(c.tag).push(c.title);
}
const tags = [...byTag.keys()].sort((a, b) => a.localeCompare(b, 'en'));

// Group puzzles by the "mate in N" phrase parsed out of their task text, N
// ascending; anything that doesn't match falls into a trailing "other" bucket.
const themeCounts = new Map();
for (const p of NG.PUZZLES) {
  const m = /mate in \d+/i.exec(p.task || '');
  const theme = m ? m[0] : 'other';
  themeCounts.set(theme, (themeCounts.get(theme) || 0) + 1);
}
const themes = [...themeCounts.keys()].sort((a, b) => {
  const na = parseInt(a.match(/\d+/), 10);
  const nb = parseInt(b.match(/\d+/), 10);
  if (isNaN(na) && isNaN(nb)) { return a.localeCompare(b, 'en'); }
  if (isNaN(na)) { return 1; }
  if (isNaN(nb)) { return -1; }
  return na - nb;
});

let md = '# Night Gallery — card index\n\n';
md += 'Generated by `npm run content-index` — do not edit by hand.\n\n';
md += '**' + NG.CONCEPTS.length + ' concept cards** across ' + tags.length +
  ' tags, plus ' + NG.PUZZLES.length + ' chess puzzles, ' +
  NG.POSITIONS.length + ' positions and ' + NG.AMBIENT_WORDS.length +
  ' ambient words.\n\n';
md += '| Tag | Cards |\n|---|---|\n';
for (const t of tags) { md += '| ' + t + ' | ' + byTag.get(t).length + ' |\n'; }
for (const t of tags) {
  md += '\n## ' + t + ' (' + byTag.get(t).length + ')\n\n';
  for (const title of byTag.get(t)) { md += '- ' + title + '\n'; }
}

md += '\n## Chess boards\n\n';
md += '### Puzzles by theme\n\n';
for (const t of themes) { md += '- ' + t + ': ' + themeCounts.get(t) + '\n'; }
md += '\n### Positions (' + NG.POSITIONS.length + ')\n\n';
for (const p of NG.POSITIONS) { md += '- ' + p.title + ' (' + p.kind + ')\n'; }

const out = path.join(root, 'docs', 'CONTENT-INDEX.md');
if (process.argv[2] === '--check') {
  const current = fs.existsSync(out) ? fs.readFileSync(out, 'utf8') : '';
  if (current !== md) {
    console.error('content-index: docs/CONTENT-INDEX.md is stale — run `npm run content-index` and stage it.');
    process.exit(1);
  }
  console.log('content-index: up to date');
} else {
  fs.writeFileSync(out, md);
  console.log('content-index: wrote docs/CONTENT-INDEX.md (' + NG.CONCEPTS.length + ' cards)');
}
